[build]
    command = "npm run build"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[redirects]]
    from = "https://spotify.thethirdwheel.fm"
    to = "https://open.spotify.com/show/4ra0nYXS9OwPU5Zl0Noyus?si=46svKgylTnCDxtbbuzoVrg"
    status = 301
    force = true

[[redirects]]
    from = "https://apple.thethirdwheel.fm"
    to = "https://podcasts.apple.com/gb/podcast/the-third-wheel/id1481766848"
    status = 301
    force = true

[[redirects]]
    from = "https://google.thethirdwheel.fm"
    to = "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9lNWYyOTNjL3BvZGNhc3QvcnNz"
    status = 301
    force = true

[[redirects]]
    from = "https://youtube.thethirdwheel.fm"
    to = "https://www.youtube.com/channel/UCuO_pWJSxq3nkWIMQa07VLg"
    status = 301
    force = true